### ISSUE TITLE
Search by Pokedex ID

### ISSUE THREAD

**Issue by JaceyFish** [Duncan-Britt/Team-Rocket#4]
As a user, I should be able to filter the Pokemon based on their Pokedex ID. The search will return the Pokemon with the corresponding ID. 

Acceptance Criteria: As a user, given the search bar , when I type in 16 into the search bar the page will return the Pokemon with the corresponding Pokedex ID of 16.

**Comment by JasonHunter95** [comment]
User can succesfully search for a pokemon by its id #.
i.e. entering 1 in the search bar returns data about bulbasaur whose pokedex index is 1,
and entering 151 will return data about the pokemon mew, whose pokedex entry is 151.
